### ISSUE TITLE
Maze Bank West Glitch

### ISSUE THREAD

**Issue by TKLeuPT** [Bob74/bob74_ipl#10]
Hello, i really love your scripts, u do an awesome work, i just noticed that the Maze Bank West interiors got glitched in the newer versions, it does work with the outdated one, would be awesome if you could fix it :D
Have a nice one, and keep up the awesome work :)

**Comment by Bob74** [comment]
Hi, can you send a screenshot of the glitch?
Is it an issue with the office or the garage ?

**Comment by TKLeuPT** [comment]
Hi, it is in the office itself, when i get inside there is invisble walls and the camera gets kinda glitched, i can send a screenshot later on 😉

**Comment by Bob74** [comment]
I guess you have the garage(s) loaded and it glitches with the office (I have this kind of issue with other garages).

Try unloading the Maze Bank West garage and maybe the mobshop too.
If the problem comes from here, you will need to disable the garages when the player enters the office and re-enabling them when he leaves.

**Comment by TKLeuPT** [comment]
I've commented these only to test, but the problem persists
ImportCEOGarage1.LoadDefault() 
ImportCEOGarage2.LoadDefault() 
ImportCEOGarage3.LoadDefault() 
ImportCEOGarage4.LoadDefault()

**Comment by Bob74** [comment]
All right, the issue comes from `ImportCEOGarage4.Part.Garage1` which overlaps with the office.
Instead of using `Garage1` by default, we should use `Garage2` (the same issue occurs using `ImportCEOGarage4.Part.Garage3`).

**Comment by Bob74** [comment]
Fixed in 2.0.7c
