### ISSUE TITLE
Some ipl's not loading?

### ISSUE THREAD

**Issue by NatalieAkiama** [Bob74/bob74_ipl#12]
Im totally a noob at this, i recently put this on my fivem server but some of the maps are not loading or something. when i look in the config files for the teleport coordinates. and i do the tp command it comes up saying invalid coordinates. is there something i am missing here?

**Comment by Bob74** [comment]
Hi, I'm quite sure the issue is related with the way you teleport to coordinates.

Indeed, this script will not "create valid coordinates". You are free to teleport outside the map or under the ground in GTA V.
You must check how your teleport script works and see if you use it correctly.
Most teleport scripts uses
```
/tp X Y Z
```
Therefore, be sure not to write a comma (`,`) between the coordinates.
