### ISSUE TITLE
Bunker not accessible 

### ISSUE THREAD

**Issue by GamingShepherd** [Bob74/bob74_ipl#157]
No teleport marker appearing to enter the bunker, Marker should appear so i can teleport into the bunker interior on foot or in a car, its not appearing for either scenario.

![Screenshot_141](https://github.com/user-attachments/assets/316618fa-a59a-41f7-9861-2c14f68b0b9b)
![Screenshot_142](https://github.com/user-attachments/assets/447f63b0-8bc2-4948-890c-fd0e453f46a0)

**Comment by alberttheprince** [comment]
You would need to do this with a separate resource. Not the purpose of Bob ipl.

**Comment by Bob74** [comment]
As alberttheprince said, this resource does not provide any way to teleport inside interiors because every server owner will have its way to teleport players.

Some will want to let anyone enter everywhere, some will restrict the entrance to some users only, it is entirely up to the server owner to setup a way to teleport players.
