### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FakeItalianMan** [Bob74/bob74_ipl#44]
Is there a way to make it so you can see inside the CEO offices from the outside like you can in normal GTA? Thanks.

**Comment by Bob74** [comment]
I don't think I follow, you can see the inside of an office from the exterior? I don't remember this in GTA:O

I know GTA:O disable some 3D models when you are inside an interior to clear the view when looking at windows (ie: it generally disable the exterior of the building you are in, otherwise you would see textures from the inside when looking outside)

Do you have an example with screenshots?

**Comment by FakeItalianMan** [comment]
What I am meaning, In normal GTA Online if someone was to be in a helicopter and fly up beside the building they could see inside through the windows this is not the case for me right now as if I no clip out of the building and look in from the outside it just shows the building but you cant see in. Does that make anymore sense? Sorry difficult to explain.

**Comment by Bob74** [comment]
To be honest I really didn't know R* added that feature and it surprises me since these interiors are the same for everyone.
They are instantiated so multiple players can be at the same physical place without seeing each others.

If no one is talking about this on the internet, I would recommend looking for decompiled scripts that mention offices (look for the IPL name or maybe parts of the 3D model name).

It still triggers me a little bit, could you please provide a screenshot? I'm really curious, I've never suspected this behavior with the interiors seen from exterior.
