### ISSUE TITLE
Gunrunning: Yacht

### ISSUE THREAD

**Issue by BraveDevelopment** [Bob74/bob74_ipl#85]
This is more of a question than an issue.
Is the yacht more configurable than in the wiki is shown? Like the type of yacht?
This would be really important i think. To switch between the 3 models : "Orion", "Pisces" and "Aquarius".
Also to change the position of the yacht... Also to change the lighting, the primary color and the accent color.

**Comment by Bob74** [comment]
I think you're talking about the Galaxy Super Yachts added in "Executives and Other Criminals":
https://gta.fandom.com/wiki/Galaxy_Super_Yacht

I didn't give much attention to these, they seems quite complicated to add, there are tons of customizations and multiple placements.

I agree it would be an nice addition to this mod but I will not be able to do this on my own, unfortunately this mod is not my priority since quite a time ^^"

**Comment by BraveDevelopment** [comment]
> 

Oh ok i didnt know this was a different one... But thank you for your reply :)

**Comment by CollapsedLegacy** [comment]
Did you end up finding the yacht hash keys?

**Comment by alberttheprince** [comment]
The yachts are just a base yacht models with various objects attached:

gr_grdlc_yacht_hull
apa_mp_apa_yacht

The different model antennas:

hei_ch1_yacht_main_telecom
hei_ch1_yacht_main_telecom_pole1
gr_grdlc_yacht_main_telecom

You would need to find these and change them, I don't think there are preset orion, pieces, and aquarius models.
